
package:
  name: my_test_pkg # must be explicitly written
  version: "0.6.0"

source:
  git_url: https://github.com/GreenfishK/test_repository.git
  git_rev: master

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=3.8
    - setuptools
    - conda
    - conda-build
    - conda-client
  run:
    - python >=3.8
    - matplotlib >=3.3.2
    - numpy >=1.18 
    - pandas >=1.1.2 


about:
  summary: "A test package"
  description: "A test package long"
  home: "https://github.com/GreenfishK/test_repository"
  license: "GNU General Public License (GPL)"


