{% set version = "0.5.0" %}

package:
  name: my_test_pkg
  version: {{ version }}

build:
  noarch: python
  number: 0

source:
  # path should later be exchanged with git_url or url:<url_to_conda-forge>
  git_url: https://github.com/GreenfishK/test_repository.git
  git_rev: master # if master is set then this will change over time and is not reproducible

requirements:
  host: 
    - python >=3.8
    - conda >=4.10
    - conda-build
    - anaconda-client
    - setuptools  >=40.9.0
    - wheel
  run:
    - python >=3.8
    - matplotlib >=3.3.2
    - numpy >=1.18 
    - pandas >=1.1.2 

about:
  license: GNU General Public License (GPL)
  summary: 'A package for testing the conda build mechanisms'

