
package:
  name: "my_test_pkg" # must be explicitly written
  version: "0.7.0"

source:
  git_url: https://github.com/GreenfishK/test_repository.git
  git_rev: master

build:
  linux-64: python
  number: 0

requirements:
  build:
    - python 3.8
    - setuptools >=49.6.0
    - conda
    - conda-build
    - anaconda-client
  run:
    - python >=3.8
    - matplotlib >=3.4.1
    - numpy >=1.20.2
    - pandas >=1.2.3


about:
  summary: "A test package"
  description: "A test package long"
  home: "https://github.com/GreenfishK/test_repository"
  license: "GNU General Public License (GPL)"


