{% set data = load_setup_py_data() %}

package:
  name: my_test_pkg # must be explicitly written
  version: "{{ data['version'] }}"

source:
  git_url: "{{ data['url'] }}.git"
  git_rev: master

build:
  # entry_points:
  #   {% for script in data['entry_points']['console_scripts'] %}
  #   - {{ script }}
  #   {% endfor %}
  noarch: python
  number: 0

requirements:
  build:
    #{% for dep in data['build'] %}
    #- {{ dep.lower() }}
    #{% endfor %}
    - python
    - conda
    - conda-build
    - setuptools
    #- anaconda-client
    #- twine
    #- wheel
  run:
    {% for req in data['install_requires'] %}
    - {{ req.lower() }}
    {% endfor %}


about:
  summary: "{{ data['description'] }}"
  description: "{{ data['description'] }}"
  home: "{{ data['url'] }}"
  license: "{{ data['license'] }}"

extra:
  recipe-maintainers: "{{ data['author'] }} <{{ data['author_email'] }}>"
