{% set data = load_setup_py_data() %}

package:
  name: my_test_pkg # must be explicitly written
  version: "{{ data['version'] }}"

source:
  git_url: "{{ data['url'] }}.git"
  git_rev: master

build:
  # entry_points:
  #   {% for script in data['entry_points']['console_scripts'] %}
  #   - {{ script }}
  #   {% endfor %}
  noarch: python
  number: 0

requirements:
  build:
    #{% for dep in data['build'] %}
    #- {{ dep.lower() }}
    #{% endfor %}
    - python 3.8
    # setuptool 46.1.3 dependencies
    - _libgcc_mutex 0.1 main
    - ca-certificates 2020.1.1 0
    - certifi 2019.11.28 py38_1
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libedit 3.1.20181209 hc058e9b_0
    - libffi 3.2.1 hd88cf55_4
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_0
    - openssl 1.1.1e h7b6447c_0
    #- python 3.8.2 hcf32534_0
    - readline 8.0 h7b6447c_0
    - sqlite 3.31.1 h7b6447c_0
    - tk 8.6.8 hbc83047_0
    - xz 5.2.4 h14c3975_4
    - zlib 1.2.11 h7b6447c_3
    #- anaconda-client
    #- twine
    #- wheel
  run:
    {% for req in data['install_requires'] %}
    - {{ req.lower() }}
    {% endfor %}


about:
  summary: "{{ data['description'] }}"
  description: "{{ data['description'] }}"
  home: "{{ data['url'] }}"
  license: "{{ data['license'] }}"

extra:
  recipe-maintainers: "{{ data['author'] }} <{{ data['author_email'] }}>"
